const DEVICE_SIZES = {
  MOBILE_SM: 320,
  MOBILE_MD: 375,
  MOBILE_LG: 425,
  TABLET_SM: 475,
  TABLET: 768,
  DESKTOP_SM: 1024,
  DESKTOP_MD: 1440,
  DESKTOP_LG: 2560,
};

const DEVICE_SIZES_PX = {
  MOBILE_SM: `${DEVICE_SIZES.MOBILE_SM}px`,
  MOBILE_MD: `${DEVICE_SIZES.MOBILE_MD}px`,
  MOBILE_LG: `${DEVICE_SIZES.MOBILE_LG}px`,
  TABLET_SM: `${DEVICE_SIZES.TABLET_SM}px`,
  TABLET: `${DEVICE_SIZES.TABLET}px`,
  DESKTOP_SM: `${DEVICE_SIZES.DESKTOP_SM}px`,
  DESKTOP_MD: `${DEVICE_SIZES.DESKTOP_MD}px`,
  DESKTOP_LG: `${DEVICE_SIZES.DESKTOP_LG}px`,
};

export { DEVICE_SIZES, DEVICE_SIZES_PX };
